name: Cypress Test
on: 
  schedule:
  - cron: "10 20 * * *"
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
     - name: Setup npm package
       run: npm init -y && npm install
            npm cypress test
